<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.ronalders</groupId>
        <artifactId>operaton-process-test-coverage-root</artifactId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>

    <groupId>io.github.ronalders</groupId>
    <artifactId>operaton-process-test-coverage-parent</artifactId>
    <version>1.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Operaton Process Test Coverage Extension Parent</name>
    <description>Parent POM for Operaton Process Test Coverage extension modules.</description>
    <url>https://github.com/ronalders/operaton-process-test-coverage</url>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Ron Alders</name>
            <email>aldersron@gmail.com</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/ronalders/operaton-process-test-coverage.git</connection>
        <developerConnection>scm:git:ssh://github.com:ronalders/operaton-process-test-coverage.git</developerConnection>
        <url>https://github.com/ronalders/operaton-process-test-coverage</url>
    </scm>

    <modules>
        <module>core</module>
        <module>engine</module>
        <module>junit5-common</module>
        <module>junit5</module>
        <module>spring-test-common</module>
        <module>spring-test</module>
        <module>starter</module>
        <module>report-generator</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- Own BOM -->
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-bom</artifactId>
                <version>${project.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <defaultGoal>clean install</defaultGoal>
    </build>

    <profiles>
        <profile>
            <id>plugins</id>
            <activation>
                <property><name>!skipPlugins</name></property>
            </activation>
            <modules>
                <module>report-aggregator-maven-plugin</module>
                <module>sonar-process-test-coverage-plugin</module>
            </modules>
        </profile>
    </profiles>

</project>
