<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.ronalders</groupId>
        <artifactId>operaton-process-test-coverage-root</artifactId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>

    <groupId>io.github.ronalders</groupId>
    <artifactId>operaton-process-test-coverage-bom</artifactId>
    <version>1.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Operaton Process Test Coverage BOM</name>
    <description>Bill of Materials for Operaton Process Test Coverage library.</description>
    <url>https://github.com/ronalders/operaton-process-test-coverage</url>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Ron Alders</name>
            <email>aldersron@gmail.com</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/ronalders/operaton-process-test-coverage.git</connection>
        <developerConnection>scm:git:ssh://github.com:ronalders/operaton-process-test-coverage.git</developerConnection>
        <url>https://github.com/ronalders/operaton-process-test-coverage</url>
    </scm>

    <dependencyManagement>
        <dependencies>
            <!-- Own modules -->
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-engine</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-junit5-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-junit5</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-spring-test-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-spring-test</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-report-generator</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.ronalders</groupId>
                <artifactId>operaton-process-test-coverage-report-aggregator-maven-plugin</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>